In [5]:
import pandas as pd
import numpy as np
from glob import glob

df = []
for csv_path in glob("data/MSD/*"):
    # if csv_path.endswith("Ts.csv"):
    #     continue
    df.append(pd.read_csv(csv_path, index_col=0))
df = pd.concat(df)

In [6]:
df

task                                            gt_path  \
0          Task10_Colon  /data/datasets/MSD/Task10_Colon/labelsTr/colon...   
1          Task10_Colon  /data/datasets/MSD/Task10_Colon/labelsTr/colon...   
2          Task10_Colon  /data/datasets/MSD/Task10_Colon/labelsTr/colon...   
3          Task10_Colon  /data/datasets/MSD/Task10_Colon/labelsTr/colon...   
4          Task10_Colon  /data/datasets/MSD/Task10_Colon/labelsTr/colon...   
..                  ...                                                ...   
515  Task04_Hippocampus  /data/datasets/MSD/Task04_Hippocampus/labelsTs...   
516  Task04_Hippocampus  /data/datasets/MSD/Task04_Hippocampus/labelsTs...   
517  Task04_Hippocampus  /data/datasets/MSD/Task04_Hippocampus/labelsTs...   
518  Task04_Hippocampus  /data/datasets/MSD/Task04_Hippocampus/labelsTs...   
519  Task04_Hippocampus  /data/datasets/MSD/Task04_Hippocampus/labelsTs...   

     obj_id  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       1.0  
..      ...  
515     2.0  
516     1.0  
517     2.0  
518     1.0  
519     2.0  

[6634 rows x 3 columns]

In [7]:
len(df) // 4

1658

In [2]:
import torch

a = torch.rand((1, 4, 2, 4))
a

tensor([[[[0.3160, 0.5735, 0.4545, 0.3598],
          [0.9225, 0.6905, 0.3593, 0.8454]],

         [[0.9821, 0.5990, 0.4059, 0.7558],
          [0.1474, 0.4174, 0.7284, 0.5023]],

         [[0.6183, 0.1904, 0.4151, 0.4566],
          [0.2731, 0.0699, 0.2593, 0.8977]],

         [[0.0269, 0.5765, 0.4509, 0.2259],
          [0.7044, 0.5836, 0.4183, 0.9869]]]])

In [15]:
torch.tensor_split(a, indices=(-1,), dim=1)

(tensor([[[[0.3160, 0.5735, 0.4545, 0.3598],
           [0.9225, 0.6905, 0.3593, 0.8454]],
 
          [[0.9821, 0.5990, 0.4059, 0.7558],
           [0.1474, 0.4174, 0.7284, 0.5023]],
 
          [[0.6183, 0.1904, 0.4151, 0.4566],
           [0.2731, 0.0699, 0.2593, 0.8977]]]]),
 tensor([[[[0.0269, 0.5765, 0.4509, 0.2259],
           [0.7044, 0.5836, 0.4183, 0.9869]]]]))