In [1]:
import torch
import scipy

In [2]:
ckpt = torch.load("/data/code/DQN-MedSAM2/checkpoints/sam2_hiera_tiny.pt")
for k in ckpt["model"].keys():
    print(k)

maskmem_tpos_enc
no_mem_embed
no_mem_pos_enc
no_obj_ptr
image_encoder.trunk.pos_embed
image_encoder.trunk.pos_embed_window
image_encoder.trunk.patch_embed.proj.weight
image_encoder.trunk.patch_embed.proj.bias
image_encoder.trunk.blocks.0.norm1.weight
image_encoder.trunk.blocks.0.norm1.bias
image_encoder.trunk.blocks.0.attn.qkv.weight
image_encoder.trunk.blocks.0.attn.qkv.bias
image_encoder.trunk.blocks.0.attn.proj.weight
image_encoder.trunk.blocks.0.attn.proj.bias
image_encoder.trunk.blocks.0.norm2.weight
image_encoder.trunk.blocks.0.norm2.bias
image_encoder.trunk.blocks.0.mlp.layers.0.weight
image_encoder.trunk.blocks.0.mlp.layers.0.bias
image_encoder.trunk.blocks.0.mlp.layers.1.weight
image_encoder.trunk.blocks.0.mlp.layers.1.bias
image_encoder.trunk.blocks.1.norm1.weight
image_encoder.trunk.blocks.1.norm1.bias
image_encoder.trunk.blocks.1.attn.qkv.weight
image_encoder.trunk.blocks.1.attn.qkv.bias
image_encoder.trunk.blocks.1.attn.proj.weight
image_encoder.trunk.blocks.1.attn.proj.bi

In [ ]:
scipy.linalg.circulant(torch.arange(4)).trans()

In [ ]:
gamma = 0.99
tau = 1
delta = torch.rand(4, 1)
coef = torch.triu(torch.full((4,4), gamma * tau)) ** torch.Tensor(scipy.linalg.circulant(torch.arange(4))).T
print(delta)
print(coef)
print(coef @ delta)

tensor([[0.5583],
        [0.9632],
        [0.9166],
        [0.0821]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[0.5583],
        [0.9632],
        [0.9166],
        [0.0821]])


In [53]:
a, b = tuple(zip(*[(1, 2), (3, 4)]))
print(a)
print(b)

(1, 3)
(2, 4)
