In [17]:
import torch
from torch import nn

from sam2_train.rl_modules.rl_blocks import SpatialSummarizer, QFormerBlock, QuickGELU, BasicTransformerBlock, CrossAttention

from collections import OrderedDict

ckpt = torch.load("output/sarcoma+grpo+perceiver/2026-01-06-20-46-56/best.pth")

sam2_params, agent_params = 0, 0

agent_params = 0
for name, param in ckpt["agent"].items():
    agent_params += param.numel()
    # print(f"{name}: {agent_params:,d}")
    
print(f"agent_params: {agent_params:,d}")
        
for k, v in ckpt["model"].items():
    if "image_encoder" in k:
        continue
    elif "sam_prompt_encoder" in k:
        continue
    # elif "mask_downsample" in k:
    #     continue
    # elif "backboneUpdate" in k:
    #     continue
    
    # if "memory_attention" in k:
    #     sam2_params += v.numel()
    #     print(f"{k}: {v.numel():,d}")
        
    # if "sam_mask_decoder" in k:
    sam2_params += v.numel()
    print(f"{k}: {v.numel():,d}")
    
print(f"sam2_params: {sam2_params:,d}")

/tmp/ipykernel_1146689/757439256.py:8: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load("output/sarcoma+grpo+perceiver/2026-01-06-20-46-56/best.pth")


agent_params: 6,927,617
maskmem_tpos_enc: 448
no_mem_embed: 256
no_mem_pos_enc: 256
no_obj_ptr: 256
mask_downsample.weight: 16
mask_downsample.bias: 1
memory_attention.layers.0.self_attn.q_proj.weight: 65,536
memory_attention.layers.0.self_attn.q_proj.bias: 256
memory_attention.layers.0.self_attn.k_proj.weight: 65,536
memory_attention.layers.0.self_attn.k_proj.bias: 256
memory_attention.layers.0.self_attn.v_proj.weight: 65,536
memory_attention.layers.0.self_attn.v_proj.bias: 256
memory_attention.layers.0.self_attn.out_proj.weight: 65,536
memory_attention.layers.0.self_attn.out_proj.bias: 256
memory_attention.layers.0.cross_attn_image.q_proj.weight: 65,536
memory_attention.layers.0.cross_attn_image.q_proj.bias: 256
memory_attention.layers.0.cross_attn_image.k_proj.weight: 16,384
memory_attention.layers.0.cross_attn_image.k_proj.bias: 256
memory_attention.layers.0.cross_attn_image.v_proj.weight: 16,384
memory_attention.layers.0.cross_attn_image.v_proj.bias: 256
memory_attention.layers.0.

In [72]:
class BaseFeatureSummarizer(nn.Module):
    def __init__(self, num_maskmem, num_support, n_query=16, image_dim=256, memory_dim=64, obj_ptr_dim=256):
        super().__init__()

        self.num_maskmem = num_maskmem
        self.num_support = num_support
        self.n_query = n_query
        self.memory_dim = memory_dim
        self.hidden_dim = n_query * memory_dim + obj_ptr_dim

        self.image_spatial_summary = SpatialSummarizer(
            n_query, self.hidden_dim, image_dim, self.hidden_dim // 128, 128, n_layers=1)
        self.memory_spatial_summary = SpatialSummarizer(
            n_query, memory_dim, memory_dim, memory_dim // 128, 128, n_layers=1)

    def forward(self, image_feat, memory_feat, memory_ptr, bank_feat, bank_ptr):
        B, T, C, H, W = bank_feat.shape

        combined_mem_feat = torch.cat([bank_feat, memory_feat.unsqueeze(1)], dim=1)
        combined_mem_feat = combined_mem_feat.reshape(B * (T+1), C, H, W)
        memory_spatial_query = self.memory_spatial_summary(combined_mem_feat)
        image_spatial_query = self.image_spatial_summary(image_feat)

        memory_spatial_query = memory_spatial_query.reshape(B, (T+1), self.n_query, self.memory_dim)
        (
            non_cond_bank_feat,
            cond_bank_feat,
            curr_mem_feat
        ) = torch.tensor_split(memory_spatial_query, indices=(self.num_maskmem, -1), dim=1)
        non_cond_obj_ptr, cond_obj_ptr = torch.tensor_split(bank_ptr, indices=(self.num_maskmem,), dim=1)

        non_cond_bank_feat = non_cond_bank_feat.flatten(2)
        cond_bank_feat = cond_bank_feat.flatten(2)
        curr_mem_feat = curr_mem_feat.flatten(2)

        non_cond_bank_feat = torch.cat([non_cond_bank_feat, non_cond_obj_ptr], dim=-1)
        cond_bank_feat = torch.cat([cond_bank_feat, cond_obj_ptr], dim=-1)
        curr_mem_feat = torch.cat([curr_mem_feat, memory_ptr.unsqueeze(1)], dim=-1)

        return image_spatial_query, non_cond_bank_feat, cond_bank_feat, curr_mem_feat

class BasePolicyNetwork(nn.Module):
    def __init__(
        self,
        query_dim,
        context_dim,
        n_layers=1
    ):
        super().__init__()
        self.hidden_dim = query_dim

        self.non_drop_embed = nn.Parameter(torch.rand(1, 1, self.hidden_dim))

        self.action_decoder = nn.ModuleList(
            [PerceiverResampler(self.hidden_dim, num_heads=1,) for _ in range(n_layers)]
        )
        self.action_proj = nn.Sequential(
            nn.LayerNorm(self.hidden_dim),
            nn.Linear(self.hidden_dim, 1)
        )

    def forward(self, image_spatial_query, non_cond_bank_feat, cond_bank_feat, curr_mem_feat, training=True):
        B = image_spatial_query.shape[0]
        non_drop_embed = self.non_drop_embed.expand(B, 1, self.hidden_dim)

        action_query = torch.cat([non_drop_embed, curr_mem_feat, non_cond_bank_feat], dim=1)
        action_context = torch.cat([cond_bank_feat, image_spatial_query], dim=1)

        for layer in self.action_decoder:
            action_query = layer(action_query, action_context)

        actions_logits = self.action_proj(action_query)
        actions_probs = torch.softmax(actions_logits, dim=1)

        return actions_probs.squeeze(-1)

class BaseValueNetwork(nn.Module):
    def __init__(
        self,
        image_dim,
        n_layers=1
    ):
        super().__init__()

        self.hidden_dim = image_dim

        self.value_query = nn.Parameter(torch.rand(1, 1, self.hidden_dim))

        self.value_decoder = nn.ModuleList(
            [PerceiverResampler(self.hidden_dim, num_heads=16) for _ in range(n_layers)]
        )
        self.value_proj = nn.Sequential(
            nn.LayerNorm(self.hidden_dim),
            nn.Linear(self.hidden_dim, 1)
        )

    def forward(self, image_spatial_query, non_cond_bank_feat, cond_bank_feat, curr_mem_feat):
        B = image_spatial_query.shape[0]
        value_query = self.value_query.expand(B, 1, self.hidden_dim)

        tokens = torch.cat([value_query, curr_mem_feat, non_cond_bank_feat, cond_bank_feat, image_spatial_query], dim=1)

        for layer in self.value_decoder:
            tokens = layer(tokens)

        return self.value_proj(tokens[:, 0, :])
    
class PerceiverResampler(nn.Module):
    def __init__(self, hidden_dim=256, num_heads=1):
        super().__init__()
        self.attn = CrossAttention(query_dim=hidden_dim, heads=num_heads, dim_head=hidden_dim // num_heads)
        self.norm1 = nn.LayerNorm(hidden_dim)
        self.mlp = nn.Sequential(OrderedDict([
            ("c_fc", nn.Linear(hidden_dim, hidden_dim * 4)),
            ("gelu", QuickGELU()),
            ("c_proj", nn.Linear(hidden_dim * 4, hidden_dim))
        ]))
        self.norm2 = nn.LayerNorm(hidden_dim)
        
        self.hidden_dim = hidden_dim
        self.num_layers = 1

class FeatureSummarizer(nn.Module):
    def __init__(self, n_query=8, hidden_dim=768, memory_dim=64, image_dim=256, num_heads=1, num_layers=1):
        super().__init__()
        self.image_resampler = nn.ModuleList([
            PerceiverResampler(hidden_dim=image_dim, num_heads=num_heads) for _ in range(num_layers)
        ])
        self.memory_resampler = nn.ModuleList([
            PerceiverResampler(hidden_dim=memory_dim, num_heads=num_heads) for _ in range(num_layers)
        ])
        
        self.image_query = nn.Parameter(torch.Tensor(1, n_query, image_dim))
        self.memory_query = nn.Parameter(torch.Tensor(1, n_query, memory_dim))
        
        self.cond_mem_proj = nn.Linear(memory_dim, image_dim)
        self.cond_obj_proj = nn.Linear(256, image_dim)
        self.non_cond_proj = nn.Linear(n_query * memory_dim + 256, image_dim)
        

In [73]:
feat_summarizer = FeatureSummarizer(n_query=16, hidden_dim=512, image_dim=256, memory_dim=64, num_heads=1, num_layers=4)
policy_net = BasePolicyNetwork(query_dim=256, context_dim=256, n_layers=4)
value_net = BaseValueNetwork(image_dim=256, n_layers=4)

agent = {
    "feat_summarizer": feat_summarizer,
    "policy_net": policy_net,
    "value_net": value_net,
}

for name, module in agent.items():
    agent_params = 0
    for k, v in module.named_parameters():
        agent_params += v.numel()
        # print(f"{k}: {v.numel():,d}")
        
    print(f"{name}: {agent_params:,d}")

feat_summarizer: 3,770,624
policy_net: 3,156,993
value_net: 3,156,993


In [1]:
import torch 

a = torch.rand(10)
a

tensor([0.3355, 0.7827, 0.6403, 0.0344, 0.6595, 0.1338, 0.9640, 0.3048, 0.1600,
        0.4298])

In [4]:
argsort = torch.argsort(a, descending=False)
rank = torch.empty_like(argsort, dtype=argsort.dtype).scatter(0, argsort, torch.arange(argsort.shape[0]))
argsort, rank

(tensor([3, 5, 8, 7, 0, 9, 2, 4, 1, 6]),
 tensor([4, 8, 6, 0, 7, 1, 9, 3, 2, 5]))

In [2]:
import pandas as pd

data = [('a', 0), ('b', 1)]
df = pd.DataFrame(data=data, columns=['char', 'int'])
df

,char,int
0,a,0
1,b,1
